export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
export const CLEAR_CART = 'CLEAR_CART';
